language: python

python:
  - '3.2'

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python3-gi gir1.2-gtk-3.0

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

virtualenv:
  system_site_packages: true

script:
  - ./run-tests
